all:
  hosts:

awsinstances:
  hosts: {}
    # server1:
    #   ansible_user: ubuntu
    #   # ansible_port: 22 # default - 22
    #   ansible_host: <host_name|ip> # 192.168.122.70


testservers:
  hosts:
    server1:
      ansible_user: canaris
      ansible_port: 8777
      ansible_host: 103.22.140.81